### ISSUE TITLE
FilteredController?

### ISSUE THREAD

**Issue by PNovak619** [CranberryAlarm/CA24_RobotCode#5]
HI - thank you for all your work on RI3D!  I was checking out your code and see DriverController extends FilteredController. I'm not familiar with FilteredController.  What is the benefit of it?  Thanks!

**Comment by snydecor000** [comment]
Hey, it's Cory from Cranberry Alarm.  FilteredController is something that Red Alert 1741 (the team that I mentor) created a few years ago to add some features on top of the GenericHID controller class.  Just for reference, we use the standard [Logitech F310 controller](https://www.logitechg.com/en-us/products/gamepads/f310-gamepad.940-000110.html) every year.

## D-pad (hat) functions

The first thing that FilteredController does is add functions for the D-pad (aka Hat) directions so that they can be used similarly to the other buttons.  For the A,B,X,Y style buttons, there is the `getRawButton()` and `getRawButtonPressed()` functions which are concise and easy to understand.  The GenericHID class though only has the `getPOV()` function for the hat which returns 0, 45, 90, 135, ... etc.  You end up writing lines like:
```
if (m_controller.getPOV() == 180) // 180 means down
{
    m_shooter.setSpeed(0.5); // 50% speed
}
```

But it would be nicer to just have functions like `getHatDown()` or `getHatDownPressed()`, so we wrote them and put them in FilteredController  :)

```
if (m_controller.getHatDown())
{
    m_shooter.setSpeed(0.5); // 50% speed
}
```

## Dead Band Axes

The second thing that FilteredController does is add the option to have joystick axis dead bands built in.  

When using GenericHID, it is common to write code like this which prevents tiny joystick movements or drift from affecting your systems:
```
if (m_controller.getRawAxis(5) > 0.03) // 3% dead band to deal with drift
{
    m_shooter.setSpeed(m_controller.getRawAxis(5);
}
```

With the FilteredController, a 3% dead band can be built into all the axes when you insatiate the controller.  Calling `getFilteredAxis()` will automatically apply the dead band:

```
FilteredController m_controller = new FilteredController(port, true /* use deadband */, false /* use squared input */)
...
m_shooter.setSpeed(m_controller.getFilteredAxis(5));
```

## Squared Input Profile

Finally, the last thing FilteredController does is add the option to have squared input profiles for the axes.  This one is less important and is really just preference of the drive team, but it can be helpful for things like drive axes.  

With a standard "linear" input profile, pushing the stick a quarter of the way = 0.25, and half way = 0.5.  
With a "squared" input profile, pushing the stick a quarter way = 0.25^2 = 0.0625, and half way = 0.5^2 = 0.25.  

It gives drivers a lot more physical range to move the joystick without the values getting large so quickly.  A very fast/touchy swerve drive would really benefit from this for example.  Of course, when you push the stick all the way, 1.0^2 still is 1.0, so you're not loosing out on any range, but if your drivers are typically either making very small/fine adjustments to the stick, or full blast sending it with the stick, then squared input profile could be very nice.
```
FilteredController m_controller = new FilteredController(port, true /* use deadband */, true /* use squared input */)
...
m_drivetrain.drive(m_controller.getFilteredAxis(1), m_controller.getFilteredAxis(2), m_controller.getFilteredAxis(3)); // x, y, rotation
```
